version: '3'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  ambassador:
    build:
      context: .
      dockerfile: Dockerfile-ambassador
    ports:
      - "80:80"
    depends_on:
      - service
